In [251]:
import pandas as pd
import pickle

In [260]:
def save_obj(obj, name ):
    with open('obj/'+ name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name ):
    with open('obj/' + name + '.pkl', 'rb') as f:
        return pickle.load(f)

In [261]:
df = pd.read_csv('19-20.csv')

In [262]:
df

,Date,Rot,VH,Team,1st,2nd,Final,Open,Close,ML,2H
0,1105,601,V,Princeton,42,25,67,144.5,142.5,190,76.5
1,1105,602,H,Duquesne,37,57,94,5.5,5.5,-240,4
2,1105,603,V,Louisville,45,42,87,7,6,-280,1
3,1105,604,H,MiamiFlorida,26,48,74,146.5,145,230,77.5
4,1105,605,V,Pennsylvania,35,46,81,146,153,275,82.5
...,...,...,...,...,...,...,...,...,...,...,...
10653,311,308370,N,NorthwesternSt,41,38,79,143.5,1,-115,77.5
10654,311,308371,N,McNeeseState,24,35,59,pk,147,115,3
10655,311,308372,N,Lamar,37,43,80,147.5,2,-135,76
10656,311,308373,V,BostonU,29,35,64,142,140.5,230,75
10657,311,308374,H,Colgate,33,28,61,7.5,6.5,-280,3

In [263]:
df = df[df['Open'] != 'NL']

In [264]:
df['Open']  = df['Open'].apply(lambda x: x.split('-')[0])

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [268]:
df['Open']  = df['Open'].apply(lambda x: x if x != "pk" else 0)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [271]:
df['Open']  = df['Open'].apply(lambda x: x if x != "PK" else 0)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [272]:
df[df['Open'] == '6-109']

Empty DataFrame
Columns: [Date, Rot, VH, Team, 1st, 2nd, Final, Open, Close, ML, 2H]
Index: []

In [274]:
df = df[df['Open'] != '']

In [275]:
df['Open'] = df['Open'].astype(float)

In [276]:
df['Final'] = df['Final'].astype(float)

In [277]:
df

,Date,Rot,VH,Team,1st,2nd,Final,Open,Close,ML,2H
0,1105,601,V,Princeton,42,25,67.0,144.5,142.5,190,76.5
1,1105,602,H,Duquesne,37,57,94.0,5.5,5.5,-240,4
2,1105,603,V,Louisville,45,42,87.0,7.0,6,-280,1
3,1105,604,H,MiamiFlorida,26,48,74.0,146.5,145,230,77.5
4,1105,605,V,Pennsylvania,35,46,81.0,146.0,153,275,82.5
...,...,...,...,...,...,...,...,...,...,...,...
10653,311,308370,N,NorthwesternSt,41,38,79.0,143.5,1,-115,77.5
10654,311,308371,N,McNeeseState,24,35,59.0,0.0,147,115,3
10655,311,308372,N,Lamar,37,43,80.0,147.5,2,-135,76
10656,311,308373,V,BostonU,29,35,64.0,142.0,140.5,230,75
10657,311,308374,H,Colgate,33,28,61.0,7.5,6.5,-280,3

In [278]:
columns = ['home','away','line','score','date']

In [279]:
df.iloc[0,3]

'Princeton'

In [283]:
home = []
away = []
home_score = []
away_score = []
date = []
lines = []
for index, row in df.iterrows():
    if index == 10385:
        break
    home1 = df.iloc[index+1,3]
    away1 = df.iloc[index,3]
    home_score1 = df.iloc[index+1,6]
    away_score1 = df.iloc[index,6]
    vh = df.iloc[index,2]
    line1 = df.iloc[index,7]
    line2 = df.iloc[index + 1,7]
    date1 = df.iloc[index ,0]
    if (index % 2) == 0:
        if vh == "V":
            home.append(home1)
            away.append(away1)
            home_score.append(home_score1)
            away_score.append(away_score1)
            date.append(date1)
            if line1 > line2:
                lines.append(line2)
            else:
                lines.append(-line1)

In [284]:
len(lines)

3745

In [285]:
len(home)

3745

In [286]:
df2 = pd.DataFrame(columns=columns)

In [287]:
df2

Empty DataFrame
Columns: [home, away, line, score, date]
Index: []

In [288]:
d = {'home': home, 'away': away, "home_score":home_score, "away_score":away_score, 'date':date, "line": lines}

In [289]:
df2 = pd.DataFrame(data=d)

In [290]:
df2

                  home             away  home_score  away_score  date  line
0             Duquesne        Princeton        94.0        67.0  1105   5.5
1         MiamiFlorida       Louisville        74.0        87.0  1105  -7.0
2              Alabama     Pennsylvania        80.0        81.0  1105   7.5
3             Michigan    AppalachianSt        79.0        71.0  1105  18.5
4              Clemson     VirginiaTech        60.0        67.0  1105   4.0
...                ...              ...         ...         ...   ...   ...
3740  NorthDakotaState      OralRoberts        75.0        69.0   309   1.0
3741       NorthDakota             IPFW        73.0        56.0   309   1.5
3742      GeorgiaState  GeorgiaSouthern        62.0        81.0   311   5.0
3743        TexasState    AppalachianSt        85.0        68.0   311   7.5
3744           Colgate          BostonU        61.0        64.0   311   7.5

[3745 rows x 6 columns]

In [291]:
def date(x):
    old = str(x)
    month = old[:2]
    day = old[2:]
    
    if month == '11' or month == '12':
        year = 2018
    else:
        month = "0" + old[:1]
        day = old[1:]
        year = 2019
    
    month = int(month)
    day = int(day)
    new = str(year)+'-'+str("{0:0=2d}".format(month))+'-'+str("{0:0=2d}".format(day))
    return new

In [292]:
df2['date'] = df2['date'].apply(lambda x: date(x))

In [293]:
df2

,home,away,home_score,away_score,date,line
0,Duquesne,Princeton,94.0,67.0,2018-11-05,5.5
1,MiamiFlorida,Louisville,74.0,87.0,2018-11-05,-7.0
2,Alabama,Pennsylvania,80.0,81.0,2018-11-05,7.5
3,Michigan,AppalachianSt,79.0,71.0,2018-11-05,18.5
4,Clemson,VirginiaTech,60.0,67.0,2018-11-05,4.0
...,...,...,...,...,...,...
3740,NorthDakotaState,OralRoberts,75.0,69.0,2019-03-09,1.0
3741,NorthDakota,IPFW,73.0,56.0,2019-03-09,1.5
3742,GeorgiaState,GeorgiaSouthern,62.0,81.0,2019-03-11,5.0
3743,TexasState,AppalachianSt,85.0,68.0,2019-03-11,7.5
3744,Colgate,BostonU,61.0,64.0,2019-03-11,7.5

In [294]:
df2['score']  = df2['home_score'] - df2['away_score']

In [295]:
df2

,home,away,home_score,away_score,date,line,score
0,Duquesne,Princeton,94.0,67.0,2018-11-05,5.5,27.0
1,MiamiFlorida,Louisville,74.0,87.0,2018-11-05,-7.0,-13.0
2,Alabama,Pennsylvania,80.0,81.0,2018-11-05,7.5,-1.0
3,Michigan,AppalachianSt,79.0,71.0,2018-11-05,18.5,8.0
4,Clemson,VirginiaTech,60.0,67.0,2018-11-05,4.0,-7.0
...,...,...,...,...,...,...,...
3740,NorthDakotaState,OralRoberts,75.0,69.0,2019-03-09,1.0,6.0
3741,NorthDakota,IPFW,73.0,56.0,2019-03-09,1.5,17.0
3742,GeorgiaState,GeorgiaSouthern,62.0,81.0,2019-03-11,5.0,-19.0
3743,TexasState,AppalachianSt,85.0,68.0,2019-03-11,7.5,17.0
3744,Colgate,BostonU,61.0,64.0,2019-03-11,7.5,-3.0

In [296]:
df2['cover'] = -99
for index, row in df2.iterrows():
    line = row['line']
    score = row['score']
    if score > line:
        win = 1
    elif score < line:
        win = 0
    else:
        win = 2
    
    
    df2.loc[index,'cover'] = win

In [297]:
df2

,home,away,home_score,away_score,date,line,score,cover
0,Duquesne,Princeton,94.0,67.0,2018-11-05,5.5,27.0,1
1,MiamiFlorida,Louisville,74.0,87.0,2018-11-05,-7.0,-13.0,0
2,Alabama,Pennsylvania,80.0,81.0,2018-11-05,7.5,-1.0,0
3,Michigan,AppalachianSt,79.0,71.0,2018-11-05,18.5,8.0,0
4,Clemson,VirginiaTech,60.0,67.0,2018-11-05,4.0,-7.0,0
...,...,...,...,...,...,...,...,...
3740,NorthDakotaState,OralRoberts,75.0,69.0,2019-03-09,1.0,6.0,1
3741,NorthDakota,IPFW,73.0,56.0,2019-03-09,1.5,17.0,1
3742,GeorgiaState,GeorgiaSouthern,62.0,81.0,2019-03-11,5.0,-19.0,0
3743,TexasState,AppalachianSt,85.0,68.0,2019-03-11,7.5,17.0,1
3744,Colgate,BostonU,61.0,64.0,2019-03-11,7.5,-3.0,0

In [306]:
len(teams)

382

In [298]:
df2.to_csv('19-20.csv',index = False)

In [299]:
df2 = pd.read_csv('19-20.csv')

In [300]:
df2

,home,away,home_score,away_score,date,line,score,cover
0,Duquesne,Princeton,94.0,67.0,2018-11-05,5.5,27.0,1
1,MiamiFlorida,Louisville,74.0,87.0,2018-11-05,-7.0,-13.0,0
2,Alabama,Pennsylvania,80.0,81.0,2018-11-05,7.5,-1.0,0
3,Michigan,AppalachianSt,79.0,71.0,2018-11-05,18.5,8.0,0
4,Clemson,VirginiaTech,60.0,67.0,2018-11-05,4.0,-7.0,0
...,...,...,...,...,...,...,...,...
3740,NorthDakotaState,OralRoberts,75.0,69.0,2019-03-09,1.0,6.0,1
3741,NorthDakota,IPFW,73.0,56.0,2019-03-09,1.5,17.0,1
3742,GeorgiaState,GeorgiaSouthern,62.0,81.0,2019-03-11,5.0,-19.0,0
3743,TexasState,AppalachianSt,85.0,68.0,2019-03-11,7.5,17.0,1
3744,Colgate,BostonU,61.0,64.0,2019-03-11,7.5,-3.0,0

In [9]:
kp = pd.read_csv('kp.csv')

In [10]:
teams_kp = kp.team.unique().tolist()

In [305]:
teams = df2.away.unique().tolist()

In [307]:
len(teams_kp)

357

In [13]:
tarik = ['SanDiego']

In [14]:
from polyfuzz import PolyFuzz

In [15]:
model = PolyFuzz("TF-IDF")

In [16]:
model.match(tarik, teams_kp)

In [17]:
df = model.get_matches()

In [303]:
df = df2

In [19]:
df.iloc[0,1]

'San Diego St.'

In [26]:
final_teams = load_obj('teams' )

In [310]:
for i in teams:
    if i in final_teams:
        continue
    test = []
    test.append(i)
    model = PolyFuzz("TF-IDF")
    model.match(test, teams_kp)
    df = model.get_matches()
    print(df)
    t1 = df.iloc[0,0]
    t2 = df.iloc[0,1]
    correct = input("is correct?: ")
    if correct == 'y':
        final_teams[t1] = t2
    elif correct == 'n':
        ask = input("actual?: ")
        final_teams[t1] = ask
    else:
        save_obj(final_teams,'teams')
        break

               From                    To  Similarity
0  UTRioGrandValley  UT Rio Grande Valley    0.627861
is correct?: y
        From         To  Similarity
0  Minnesota  Minnesota         1.0
is correct?: y
                 From                   To  Similarity
0  CentralConnecticut  Central Connecticut    0.921271
is correct?: y
                   From                      To  Similarity
0  NorthCarolinaCentral  North Carolina Central    0.805618
is correct?: y
              From              To  Similarity
0  NorthCarolinaAT  North Carolina    0.719146
is correct?: y
            From                To  Similarity
0  PrairieViewAM  Prairie View A&M    0.772902
is correct?: djfjsdf

In [309]:
final_teams

{'Towson': 'Towson',
 'WiscMilwaukee': 'Milwaukee',
 'YoungstownState': 'Youngstown St.',
 'IllinoisChicago': 'Illinois Chicago',
 'DetroitU': 'Detroit',
 'ClevelandState': 'Cleveland St.',
 'Pennsylvania': 'Penn',
 'IndianaState': 'Indiana St.',
 'SouthAlabama': 'South Alabama',
 'LaSalle': 'La Salle',
 'Delaware': 'Delaware',
 'LouisianaTech': 'Louisiana Tech',
 'IUPUI': 'IUPUI',
 'CSFullerton': 'Cal St. Fullerton',
 'Florida': 'Florida',
 'NewMexico': 'New Mexico',
 'CalRiverside': 'UC Riverside',
 'SanFrancisco': 'San Francisco',
 'CalSantaBarb': 'UC Santa Barbara',
 'WesternKentucky': 'Western Kentucky',
 'BYU': 'BYU',
 'Siena': 'Siena',
 'Rider': 'Rider',
 'Chattanooga': 'Chattanooga',
 'TheCitadel': 'The Citadel',
 'Fairfield': 'Fairfield',
 'E.Washington': 'Eastern Washington',
 'ETennesseeSt': 'East Tennessee St.',
 'NorthCarolina': 'North Carolina',
 'Mercer': 'Mercer',
 'TennesseeTech': 'Tennessee Tech',
 'NebraskaOmaha': 'Nebraska Omaha',
 'OralRoberts': 'Oral Roberts',
 'SEMissouriSt': 'Southeast Missouri St.',
 'Pacific': 'Pacific',
 'EasternIllinois': 'Eastern Illinois',
 'WesternIllinois': 'Western Illinois',
 'Elon': 'Elon',
 'IPFW': 'Purdue Fort Wayne',
 'UtahState': 'Utah St.',
 'IdahoU': 'Idaho',
 'WeberState': 'Weber St.',
 'PortlandState': 'Portland St.',
 'IdahoState': 'Idaho St.',
 'RobertMorris': 'Robert Morris',
 'BethuneCookman': 'Bethune Cookman',
 'NewOrleansU': 'New Orleans',
 'Maine': 'Maine',
 'SoIllinois': 'Southern Illinois',
 'Stanford': 'Stanford',
 'JamesMadison': 'James Madison',
 'WashingtonU': 'Washington',
 'NorthernKentucky': 'Northern Kentucky',
 'Rice': 'Rice',
 'AirForce': 'Air Force',
 'SanDiego': 'San Diego',
 'Yale': 'Yale',
 'LongBeachState': 'Long Beach St.',
 'PortlandU': 'Portland',
 'Maryland': 'Maryland',
 'VMI': 'VMI',
 'NCGreensboro': 'UNC Greensboro',
 'Furman': 'Furman',
 'AustinPeay': 'Austin Peay',
 'MontanaState': 'Montana St.',
 'JacksonvilleSt': 'Jacksonville St.',
 'GeorgiaState': 'Georgia St.',
 'CharlestonSou': 'Charleston Southern',
 'SavannahState': 'None',
 'William&Mary': 'William & Mary',
 'WesternMichigan': 'Western Michigan',
 'BallState': 'Ball St.',
 'Troy': 'Troy',
 'Evansville': 'Evansville',
 'MiamiOhio': 'Miami OH',
 'OklahomaState': 'Oklahoma St.',
 'NorthernIowa': 'Northern Iowa',
 'Wyoming': 'Wyoming',
 'NorthTexas': 'North Texas',
 'LoyolaMarymount': 'Loyola Marymount',
 'KentState': 'Kent St.',
 'MoreheadState': 'Morehead St.',
 'CollCharleston': 'Charleston',
 'TennMartin': 'Tennessee Martin',
 'Columbia': 'Columbia',
 'EasternKentucky': 'Eastern Kentucky',
 'NorthDakota': 'North Dakota',
 'Quinnipiac': 'Quinnipiac',
 'IllinoisState': 'Illinois St.',
 'WrightState': 'Wright St.',
 'SouthernUtah': 'Southern Utah',
 'CentralConn': 'Central Connecticut',
 'AppalachianSt': 'Appalachian St.',
 'Hofstra': 'Hofstra',
 'GeoWashington': 'George Washington',
 'FlaAtlantic': 'Florida Atlantic',
 'WiscGreenBay': 'Green Bay',
 'Drexel': 'Drexel',
 'SouthernMiss': 'Southern Miss',
 'RhodeIsland': 'Rhode Island',
 'GeorgeMason': 'George Mason',
 'MemphisU': 'Memphis',
 'Harvard': 'Harvard',
 'Georgia': 'Georgia',
 'Drake': 'Drake',
 'CoastalCarolina': 'Coastal Carolina',
 'Georgetown': 'Georgetown',
 'CSNorthridge': 'Cal St. Northridge',
 'GeorgiaTech': 'Georgia Tech',
 'ArkansasLR': 'Little Rock',
 'Iona': 'Iona',
 'Pepperdine': 'Pepperdine',
 'StephenF.Austin': 'Stephen F. Austin',
 'HolyCross': 'Holy Cross',
 'UMassLowell': 'UMass Lowell',
 'Southern': 'Southern',
 'Hampton': 'Hampton',
 'Michigan': 'Michigan',
 'Toledo': 'Toledo',
 'EasternMichigan': 'Eastern Michigan',
 'ULMonroe': 'Louisiana Monroe',
 'OhioState': 'Ohio St.',
 'NCCentral': 'North Carolina Central',
 'CentralArkansas': 'Central Arkansas',
 'Hartford': 'Hartford',
 'Belmont': 'Belmont',
 'ULLafayette': 'Lafayette',
 'Niagara': 'Niagara',
 'NichollsState': 'Nicholls St.',
 'CaliforniaBaptist': 'Cal Baptist',
 'Binghamton': 'Binghamton',
 'SamHoustonSt': 'Sam Houston St.',
 'AlcornState': 'Alcorn St.',
 'Radford': 'Radford',
 'NorthAlabama': 'North Alabama',
 'Wagner': 'Wagner',
 'Presbyterian': 'Presbyterian',
 'BostonU': 'Boston University',
 'NorthwesternSt': 'Northwestern St.',
 'PrairieViewA&M': 'Prairie View A&M',
 'NorthFlorida': 'North Florida',
 'UCDavis': 'UC Davis',
 'AlbanyNY': 'Albany',
 'Wofford': 'Wofford',
 'Samford': 'Samford',
 'NorthernArizona': 'Northern Arizona',
 'TexasSouthern': 'Texas Southern',
 'SacredHeart': 'Sacred Heart',
 'SoCarolinaSt': 'South Carolina St.',
 'Bryant': 'Bryant',
 'St.FrancisNY': 'St. Francis NY',
 'Jacksonville': 'Jacksonville',
 'Army': 'Army',
 'MountStMarys': "Mount St. Mary's",
 'LongIsland': 'LIU',
 'CalPolySLO': 'Cal Poly',
 'LoyolaMaryland': 'Loyola MD',
 'Canisius': 'Canisius',
 'JacksonState': 'Jackson St.',
 'CoppinState': 'Coppin St.',
 'N.CarolinaA&T': 'North Carolina A&T',
 'St.FrancisPA': 'St. Francis PA',
 'Duquesne': 'Duquesne',
 'Colorado': 'Colorado',
 'BowlingGreen': 'Bowling Green',
 'Bradley': 'Bradley',
 "St.Peter's": "Saint Peter's",
 'TennesseeState': 'Tennessee St.',
 'SacramentoState': 'Sacramento St.',
 'NJIT': 'NJIT',
 'SELouisiana': 'Southeastern Louisiana',
 'MDEasternShore': 'Maryland Eastern Shore',
 'Navy': 'Navy',
 'Lipscomb': 'Lipscomb',
 'Marist': 'Marist',
 'SaintLouis': 'Saint Louis',
 'Dartmouth': 'Dartmouth',
 'MinnesotaU': 'Minnesota',
 'TexSanAntonio': 'UTSA',
 'USCUpstate': 'USC Upstate',
 'SIUEdwardsville': 'SIU Edwardsville',
 'Winthrop': 'Winthrop',
 'Lehigh': 'Lehigh',
 'FairDickinson': 'Fairleigh Dickinson',
 'Colgate': 'Colgate',
 'FloridaA&M': 'Florida A&M',
 'UTRioGrandeValley': 'UT Rio Grande Valley',
 'No.Colorado': 'Northern Colorado',
 'AlabamaState': 'Alabama St.',
 'Oklahoma': 'Oklahoma',
 'Dayton': 'Dayton',
 'Butler': 'Butler',
 'Marshall': 'Marshall',
 'UTArlington': 'UT Arlington',
 'DenverU': 'Denver',
 'AbileneChristian': 'Abilene Christian',
 'HoustonBaptist': 'Houston Baptist',
 'Howard': 'Howard',
 'AlabamaA&M': 'Alabama A&M',
 'Lamar': 'Lamar',
 'Depaul': 'DePaul',
 'Northeastern': 'Northeastern',
 'St.Josephs': "Saint Joseph's",
 'SantaClara': 'Santa Clara',
 'Valparaiso': 'Valparaiso',
 'UTEP': 'UTEP',
 'HoustonU': 'Houston',
 'TexasState': 'Texas St.',
 'Princeton': 'Princeton',
 'Manhattan': 'Manhattan',
 'NorthDakotaState': 'North Dakota St.',
 'MissouriSt': 'Missouri St.',
 'American': 'American',
 'StonyBrook': 'Stony Brook',
 'ChicagoSt': 'Chicago St.',
 'ArkPineBluff': 'Arkansas Pine Bluff',
 'DelawareState': 'Delaware St.',
 'OregonState': 'Oregon St.',
 'Longwood': 'Longwood',
 'MissValleySt': 'Mississippi Valley St.',
 'Bucknell': 'Bucknell',
 'Lafayette': 'Lafayette',
 'IncarnateWord': 'Incarnate Word',
 'FlaGulfCoast': 'Florida Gulf Coast',
 'CSBakersfield': 'Cal St. Bakersfield',
 'Nebraska': 'Nebraska',
 'MurrayState': 'Murray St.',
 'Stetson': 'Stetson',
 'TexasA&MCorpus': 'Texas A&M Corpus Chris',
 'CharlotteU': 'Charlotte',
 'EastCarolina': 'East Carolina',
 'Illinois': 'Illinois',
 'VirginiaTech': 'Virginia Tech',
 'MichiganState': 'Michigan St.',
 'BoiseState': 'Boise St.',
 'Nevada': 'Nevada',
 'Pittsburgh': 'Pittsburgh',
 'Temple': 'Temple',
 'NCState': 'N.C. State',
 'IndianaU': 'Indiana',
 'WesternCarolina': 'Western Carolina',
 'SouthDakota': 'South Dakota',
 'HighPoint': 'High Point',
 'KennesawSt': 'Kennesaw St.',
 'Grambling': 'Grambling St.',
 'NewMexicoState': 'New Mexico St.',
 'UMKC': 'UMKC',
 'FloridaState': 'Florida St.',
 'Providence': 'Providence',
 'OldDominion': 'Old Dominion',
 'Creighton': 'Creighton',
 'Baylor': 'Baylor',
 'IowaState': 'Iowa St.',
 'NCAsheville': 'UNC Asheville',
 'MorganState': 'Morgan St.',
 'NorfolkSt': 'Norfolk St.',
 'Auburn': 'Auburn',
 'MississippiSt': 'Mississippi St.',
 'Villanova': 'Villanova',
 'CentralMichigan': 'Central Michigan',
 'Clemson': 'Clemson',
 'TexasTech': 'Texas Tech',
 'NotreDame': 'Notre Dame',
 'Buffalo': 'Buffalo',
 'WichitaState': 'Wichita St.',
 'TexasA&M': 'Texas A&M',
 'WakeForest': 'Wake Forest',
 'Duke': 'Duke',
 'Mississippi': 'Mississippi',
 'SanDiegoState': 'San Diego St.',
 'Purdue': 'Purdue',
 'St.Bonaventure': 'St. Bonaventure',
 'Richmond': 'Richmond',
 'Texas': 'Texas',
 'VaCommonwealth': 'VCU',
 'Tennessee': 'Tennessee',
 'FloridaIntl': 'FIU',
 'CentralFlorida': 'UCF',
 'Missouri': 'Missouri',
 'LoyolaChicago': 'Loyola Chicago',
 'Wisconsin': 'Wisconsin',
 'SanJoseState': 'San Jose St.',
 'ColoradoState': 'Colorado St.',
 'CalIrvine': 'UC Irvine',
 'NewHampshire': 'New Hampshire',
 'MDBaltimoreCo': 'UMBC',
 'Oakland': 'Oakland',
 'Tulsa': 'Tulsa',
 'MiamiFlorida': 'Miami FL',
 'MiddleTennSt': 'Middle Tennessee',
 'UAB': 'UAB',
 'UtahU': 'Utah',
 'Arizona': 'Arizona',
 'SaintMarysCA': "Saint Mary's",
 'ArizonaState': 'Arizona St.',
 'Gonzaga': 'Gonzaga',
 'WashingtonState': 'Washington St.',
 'Monmouth': 'Monmouth',
 'GardnerWebb': 'Gardner Webb',
 'UtahValley': 'Utah Valley',
 'SeattleU': 'Seattle',
 'Brown': 'Brown',
 'Alabama': 'Alabama',
 'Virginia': 'Virginia',
 'KansasState': 'Kansas St.',
 'Marquette': 'Marquette',
 'SouthCarolina': 'South Carolina',
 'Northwestern': 'Northwestern',
 'SouthFlorida': 'South Florida',
 'Vanderbilt': 'Vanderbilt',
 'BostonCollege': 'Boston College',
 'WestVirginia': 'West Virginia',
 'FresnoState': 'Fresno St.',
 'Rutgers': 'Rutgers',
 'NoIllinois': 'Northern Illinois',
 'LSU': 'LSU',
 'Arkansas': 'Arkansas',
 'Kansas': 'Kansas',
 'Cornell': 'Cornell',
 'Syracuse': 'Syracuse',
 'Campbell': 'Campbell',
 'Vermont': 'Vermont',
 'GrandCanyon': 'Grand Canyon',
 'Cincinnati': 'Cincinnati',
 'SetonHall': 'Seton Hall',
 'Iowa': 'Iowa',
 'Liberty': 'Liberty',
 'TCU': 'TCU',
 'Ohio': 'Ohio',
 'Kentucky': 'Kentucky',
 'Massachusetts': 'Massachusetts',
 'Louisville': 'Louisville',
 'St.Johns': "St. John's",
 'SMU': 'SMU',
 'UCLA': 'UCLA',
 'USC': 'USC',
 'Tulane': 'Tulane',
 'Xavier': 'Xavier',
 'Connecticut': 'Connecticut',
 'Oregon': 'Oregon',
 'SouthDakotaState': 'South Dakota St.',
 'Davidson': 'Davidson',
 'GeorgiaSouthern': 'Georgia Southern',
 'Akron': 'Akron',
 'UNLV': 'UNLV',
 'ArkansasState': 'Arkansas St.',
 'Montana': 'Montana',
 'PennState': 'Penn St.',
 'Fordham': 'Fordham',
 'California': 'California',
 'McNeeseState': 'McNeese St.',
 'NCWilmington': 'UNC Wilmington',
 'Hawaii': 'Hawaii',
 'UL-Lafayette': 'Lafayette',
 'AppalachianState': 'Appalachian St.',
 'Merrimack': 'Merrimack',
 'Washington': 'Washington'}

In [76]:
len(final_teams)

353

In [304]:
df2

,home,away,home_score,away_score,date,line,score,cover
0,Duquesne,Princeton,94.0,67.0,2018-11-05,5.5,27.0,1
1,MiamiFlorida,Louisville,74.0,87.0,2018-11-05,-7.0,-13.0,0
2,Alabama,Pennsylvania,80.0,81.0,2018-11-05,7.5,-1.0,0
3,Michigan,AppalachianSt,79.0,71.0,2018-11-05,18.5,8.0,0
4,Clemson,VirginiaTech,60.0,67.0,2018-11-05,4.0,-7.0,0
...,...,...,...,...,...,...,...,...
3740,NorthDakotaState,OralRoberts,75.0,69.0,2019-03-09,1.0,6.0,1
3741,NorthDakota,IPFW,73.0,56.0,2019-03-09,1.5,17.0,1
3742,GeorgiaState,GeorgiaSouthern,62.0,81.0,2019-03-11,5.0,-19.0,0
3743,TexasState,AppalachianSt,85.0,68.0,2019-03-11,7.5,17.0,1
3744,Colgate,BostonU,61.0,64.0,2019-03-11,7.5,-3.0,0

In [197]:
df2['home'] = df2['home'].apply(lambda x: final_teams[x])

KeyError: 'Boston College'

In [198]:
df2['away'] = df2['away'].apply(lambda x: final_teams[x])

KeyError: 'Milwaukee'

In [201]:
df2

,home,away,home_score,away_score,date,line,score,cover
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1
...,...,...,...,...,...,...,...,...
2711,Marshall,Green Bay,90.0,70.0,2019-04-04,5.5,20.0,1
2712,DePaul,South Florida,65.0,77.0,2019-04-05,2.0,-12.0,0
2713,Michigan St.,Texas Tech,51.0,61.0,2019-04-06,2.5,-10.0,0
2714,Virginia,Auburn,63.0,62.0,2019-04-06,5.0,1.0,0
2715,Virginia,Texas Tech,85.0,77.0,2019-04-08,1.0,8.0,1

In [155]:
df2.to_csv('18-19.csv', index = False)

In [202]:
df2

,home,away,home_score,away_score,date,line,score,cover
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1
...,...,...,...,...,...,...,...,...
2711,Marshall,Green Bay,90.0,70.0,2019-04-04,5.5,20.0,1
2712,DePaul,South Florida,65.0,77.0,2019-04-05,2.0,-12.0,0
2713,Michigan St.,Texas Tech,51.0,61.0,2019-04-06,2.5,-10.0,0
2714,Virginia,Auburn,63.0,62.0,2019-04-06,5.0,1.0,0
2715,Virginia,Texas Tech,85.0,77.0,2019-04-08,1.0,8.0,1

In [206]:
from datetime import datetime
from datetime import timedelta
import os
path = os.getcwd()
import pandas as pd
from kenpompy.utils import login
from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait # available since 2.4.0
from selenium.webdriver.support import expected_conditions as EC # available since 2.26.0
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

# Returns an authenticated browser that can then be used to scrape pages that require authorization.
browser = login('tarik0219@yahoo.com', 'kenporn123')
import kenpompy.FanMatch as fm

In [207]:
def kenpom(year, month ,day):
    options = webdriver.ChromeOptions() 
    #options.add_argument(r'''user-data-dir=C:\Users\Tarik's PC\AppData\Local\Google\Chrome\User Data''')
    #"user-data-dir=C:\Users\Tarik's PC\AppData\Local\Google\Chrome\User Data" home
    # "user-data-dir=C:\Users\koric1\AppData\Local\Google\Chrome\User Data" work
    #options.add_argument("--start-maximized")
    #self.options.add_argument("--headless")
    #self.options.add_argument("--no-sandbox")
    #self.options.add_argument("--disable-gpu")
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')  # Last I checked this was necessa
    driver = webdriver.Chrome(chrome_options= options)

    driver.get('https://kenpom.com/')
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="login"]/input[1]').send_keys('tarik0219@yahoo.com')
    driver.find_element_by_xpath('//*[@id="login"]/input[2]').send_keys('kenporn123')
    driver.find_element_by_xpath('//*[@id="login"]/input[3]').click()
    
    date = str(year)+'-'+str("{0:0=2d}".format(month))+'-'+str("{0:0=2d}".format(day))

    
        
    driver.get('https://kenpom.com/archive.php?d='+date)
    time.sleep(10)
    team = []
    off = []
    deff = []
    tempo = []
    dates = []
    for x in range(1,10):
        try:
            for z in range(1,41):
                team_name = str(driver.find_element_by_xpath('//*[@id="ratings-table"]/tbody['+str(x)+']/tr['+str(z)+']/td[2]/a').text)
                team_off = float(driver.find_element_by_xpath('//*[@id="ratings-table"]/tbody['+str(x)+']/tr['+str(z)+']/td[5]').text)
                team_def = float(driver.find_element_by_xpath('//*[@id="ratings-table"]/tbody['+str(x)+']/tr['+str(z)+']/td[7]').text)
                team_t = float(driver.find_element_by_xpath('//*[@id="ratings-table"]/tbody['+str(x)+']/tr['+str(z)+']/td[9]').text)
                #print(team_name,team_off,team_def,team_t,team_luck)
                team.append(team_name)
                off.append(team_off)
                deff.append(team_def)
                tempo.append(team_t)
                dates.append(date)
        except:
            break
    driver.close()
    d = {'team': team, 'off': off, "def":deff, "tempo":tempo, 'date':date}
    df2 = pd.DataFrame(data=d)
    return df2

In [208]:
kp = kenpom(2018, 11 ,6)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: use options instead of chrome_options
  if sys.path[0] == '':

In [209]:
kp.head()

             team    off   def  tempo        date
0          Kansas  116.5  87.3   74.0  2018-11-06
1        Virginia  112.5  86.9   66.5  2018-11-06
2            Duke  115.4  89.9   74.0  2018-11-06
3  North Carolina  115.5  90.1   75.8  2018-11-06
4       Villanova  116.3  91.5   73.0  2018-11-06

In [210]:
df2.head()

,home,away,home_score,away_score,date,line,score,cover
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1

In [211]:
df2 = pd.merge(df2, kp, how='left', left_on=['home','date'], right_on=['team','date'])
df2 = pd.merge(df2, kp, how='left', left_on=['away','date'], right_on=['team','date'])

In [212]:
df2

,home,away,home_score,away_score,date,line,score,cover,team_x,off_x,def_x,tempo_x,team_y,off_y,def_y,tempo_y
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1,Virginia,112.5,86.9,66.5,Towson,96.8,101.8,72.6
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1,Boston College,106.4,95.6,74.4,Milwaukee,95.7,103.0,71.5
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1,Pittsburgh,101.3,98.9,70.5,Youngstown St.,94.0,108.0,75.3
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1,Notre Dame,107.9,96.4,71.2,Illinois Chicago,98.5,100.6,76.5
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1,Western Michigan,99.0,103.1,73.0,Detroit,94.5,109.2,75.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2711,Marshall,Green Bay,90.0,70.0,2019-04-04,5.5,20.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2712,DePaul,South Florida,65.0,77.0,2019-04-05,2.0,-12.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2713,Michigan St.,Texas Tech,51.0,61.0,2019-04-06,2.5,-10.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2714,Virginia,Auburn,63.0,62.0,2019-04-06,5.0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2715,Virginia,Texas Tech,85.0,77.0,2019-04-08,1.0,8.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
test = fm.FanMatch(browser, date = str(2018)+'-'+str("{0:0=2d}".format(11))+'-'+str("{0:0=2d}".format(6)))

In [166]:
df = test.fm_df

In [168]:
pd.set_option('display.max_columns', 500)

In [170]:
df.dropna(subset=['PredictedScore'], inplace = True)

In [171]:
df

,Game,Location,ThrillScore,Comeback,Excitement,ThrillScoreRank,ExcitementRank,ComebackRank,MVP,Possessions,PredictedWinner,PredictedScore,WinProbability,PredictedMOV,PredictedLoser,OT,Loser,LoserRank,LoserScore,Winner,WinnerRank,WinnerScore,ActualMOV
0,"3 Duke 118, 6 Kentucky 84","Indianapolis, IN Bankers Life Fieldhouse",85.5,0,0.22,1,NaN,NaN,Zion Williamson (28p/7r/2a/1b/1s),82,Duke,78-77,53%,1.0,Kentucky,nan,Kentucky,6,84,Duke,3,118,34
1,"1 Kansas 92, 13 Michigan St. 87","Indianapolis, IN Bankers Life Fieldhouse",73.8,2,0.29,2,NaN,NaN,Dedric Lawson (20p/14r/6a/2b/2s),85,Kansas,79-72,72%,7.0,Michigan St.,nan,Michigan St.,13,87,Kansas,1,92,5
2,"15 Florida St. 81, 20 Florida 60","Tallahassee, FL Donald L. Tucker Center",71.8,4,0.43,3,NaN,NaN,PJ Savoy (20p/3r/1a/1b),72,Florida St.,79-74,65%,5.0,Florida,nan,Florida,20,60,Florida St.,15,81,21
3,"45 Washington 73, 80 Western Kentucky 55","Seattle, WA Alaska Airlines Arena",49.2,9,1.27,4,NaN,NaN,Noah Dickerson (18p/6r/2b),70,Washington,80-73,73%,7.0,Western Kentucky,nan,Western Kentucky,80,55,Washington,45,73,18
4,"70 UCF 84, 99 Rider 70","Orlando, FL CFE Federal Credit Union Arena",44.1,7,0.80,5,NaN,NaN,BJ Taylor (22p/2r/4a/1s),80,UCF,76-70,73%,6.0,Rider,nan,Rider,99,70,UCF,70,84,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,"5 Villanova 100, 343 Morgan St. 77","Villanova, PA Finneran Pavilion",7.49,0,-0.62,0,NaN,NaN,Eric Paschall (26p/7r/1a/2s),78,Villanova,93-57,99.9%,36.0,Morgan St.,nan,Morgan St.,343,77,Villanova,5,100,23
90,"50 Alabama 82, 342 Southern 62","Tuscaloosa, AL Coleman Coliseum",7.49,2,-0.57,1,NaN,NaN,Donta Hall (20p/5r/1a/2b),73,Alabama,83-57,99%,26.0,Southern,nan,Southern,342,62,Alabama,50,82,20
91,"27 Indiana 104, 344 Chicago St. 55","Bloomington, IN Assembly Hall",7.39,1,-0.61,2,NaN,NaN,Romeo Langford (19p/4r/3a/1s),81,Indiana,88-59,99.7%,29.0,Chicago St.,nan,Chicago St.,344,55,Indiana,27,104,49
92,"38 Nebraska 106, 348 Mississippi Valley St. 37","Lincoln, NE Pinnacle Bank Arena",7.39,0,-0.63,3,NaN,NaN,Glynn Watson (19p/3r/3a/1s),78,Nebraska,90-61,99.6%,29.0,Mississippi Valley St.,nan,Mississippi Valley St.,348,37,Nebraska,38,106,69
93,"19 Wisconsin 85, 349 Coppin St. 63","Madison, WI Kohl Center",6.69,5,-0.62,4,NaN,NaN,Ethan Happ (10p/11r/12a/4b),68,Wisconsin,84-53,99.8%,31.0,Coppin St.,nan,Coppin St.,349,63,Wisconsin,19,85,22

In [172]:
df['pw'] = df['PredictedScore'].apply(lambda x: x.split('-')[0])
df['pl'] = df['PredictedScore'].apply(lambda x: x.split('-')[1])

In [174]:
df['date'] = str(2018)+'-'+str("{0:0=2d}".format(11))+'-'+str("{0:0=2d}".format(6))

In [175]:
df

,Game,Location,ThrillScore,Comeback,Excitement,ThrillScoreRank,ExcitementRank,ComebackRank,MVP,Possessions,PredictedWinner,PredictedScore,WinProbability,PredictedMOV,PredictedLoser,OT,Loser,LoserRank,LoserScore,Winner,WinnerRank,WinnerScore,ActualMOV,pw,pl,date
0,"3 Duke 118, 6 Kentucky 84","Indianapolis, IN Bankers Life Fieldhouse",85.5,0,0.22,1,NaN,NaN,Zion Williamson (28p/7r/2a/1b/1s),82,Duke,78-77,53%,1.0,Kentucky,nan,Kentucky,6,84,Duke,3,118,34,78,77,2018-11-06
1,"1 Kansas 92, 13 Michigan St. 87","Indianapolis, IN Bankers Life Fieldhouse",73.8,2,0.29,2,NaN,NaN,Dedric Lawson (20p/14r/6a/2b/2s),85,Kansas,79-72,72%,7.0,Michigan St.,nan,Michigan St.,13,87,Kansas,1,92,5,79,72,2018-11-06
2,"15 Florida St. 81, 20 Florida 60","Tallahassee, FL Donald L. Tucker Center",71.8,4,0.43,3,NaN,NaN,PJ Savoy (20p/3r/1a/1b),72,Florida St.,79-74,65%,5.0,Florida,nan,Florida,20,60,Florida St.,15,81,21,79,74,2018-11-06
3,"45 Washington 73, 80 Western Kentucky 55","Seattle, WA Alaska Airlines Arena",49.2,9,1.27,4,NaN,NaN,Noah Dickerson (18p/6r/2b),70,Washington,80-73,73%,7.0,Western Kentucky,nan,Western Kentucky,80,55,Washington,45,73,18,80,73,2018-11-06
4,"70 UCF 84, 99 Rider 70","Orlando, FL CFE Federal Credit Union Arena",44.1,7,0.80,5,NaN,NaN,BJ Taylor (22p/2r/4a/1s),80,UCF,76-70,73%,6.0,Rider,nan,Rider,99,70,UCF,70,84,14,76,70,2018-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,"5 Villanova 100, 343 Morgan St. 77","Villanova, PA Finneran Pavilion",7.49,0,-0.62,0,NaN,NaN,Eric Paschall (26p/7r/1a/2s),78,Villanova,93-57,99.9%,36.0,Morgan St.,nan,Morgan St.,343,77,Villanova,5,100,23,93,57,2018-11-06
90,"50 Alabama 82, 342 Southern 62","Tuscaloosa, AL Coleman Coliseum",7.49,2,-0.57,1,NaN,NaN,Donta Hall (20p/5r/1a/2b),73,Alabama,83-57,99%,26.0,Southern,nan,Southern,342,62,Alabama,50,82,20,83,57,2018-11-06
91,"27 Indiana 104, 344 Chicago St. 55","Bloomington, IN Assembly Hall",7.39,1,-0.61,2,NaN,NaN,Romeo Langford (19p/4r/3a/1s),81,Indiana,88-59,99.7%,29.0,Chicago St.,nan,Chicago St.,344,55,Indiana,27,104,49,88,59,2018-11-06
92,"38 Nebraska 106, 348 Mississippi Valley St. 37","Lincoln, NE Pinnacle Bank Arena",7.39,0,-0.63,3,NaN,NaN,Glynn Watson (19p/3r/3a/1s),78,Nebraska,90-61,99.6%,29.0,Mississippi Valley St.,nan,Mississippi Valley St.,348,37,Nebraska,38,106,69,90,61,2018-11-06
93,"19 Wisconsin 85, 349 Coppin St. 63","Madison, WI Kohl Center",6.69,5,-0.62,4,NaN,NaN,Ethan Happ (10p/11r/12a/4b),68,Wisconsin,84-53,99.8%,31.0,Coppin St.,nan,Coppin St.,349,63,Wisconsin,19,85,22,84,53,2018-11-06

In [176]:
df.columns

Index(['Game', 'Location', 'ThrillScore', 'Comeback', 'Excitement',
       'ThrillScoreRank', 'ExcitementRank', 'ComebackRank', 'MVP',
       'Possessions', 'PredictedWinner', 'PredictedScore', 'WinProbability',
       'PredictedMOV', 'PredictedLoser', 'OT', 'Loser', 'LoserRank',
       'LoserScore', 'Winner', 'WinnerRank', 'WinnerScore', 'ActualMOV', 'pw',
       'pl', 'date'],
      dtype='object')

In [177]:
df.drop(['Game', 'Location', 'ThrillScore', 'Comeback', 'Excitement',
       'ThrillScoreRank', 'ExcitementRank', 'ComebackRank', 'MVP',
       'Possessions', 'PredictedScore', 'WinProbability',
       'PredictedMOV', 'PredictedLoser', 'OT', 'Loser', 'LoserRank',
       'LoserScore', 'Winner', 'WinnerRank', 'WinnerScore', 'ActualMOV'], axis = 1, inplace = True)

In [178]:
df

   PredictedWinner  pw  pl        date
0             Duke  78  77  2018-11-06
1           Kansas  79  72  2018-11-06
2      Florida St.  79  74  2018-11-06
3       Washington  80  73  2018-11-06
4              UCF  76  70  2018-11-06
..             ...  ..  ..         ...
89       Villanova  93  57  2018-11-06
90         Alabama  83  57  2018-11-06
91         Indiana  88  59  2018-11-06
92        Nebraska  90  61  2018-11-06
93       Wisconsin  84  53  2018-11-06

[94 rows x 4 columns]

In [213]:
def prediciton(year,month,day):
    browser = login('tarik0219@yahoo.com', 'kenporn123')
    import kenpompy.FanMatch as fm
    test = fm.FanMatch(browser, date = str(year)+'-'+str("{0:0=2d}".format(month))+'-'+str("{0:0=2d}".format(day)))
    df = test.fm_df
    df.dropna(subset=['PredictedScore'], inplace = True)
    df['pw'] = df['PredictedScore'].apply(lambda x: x.split('-')[0])
    df['pl'] = df['PredictedScore'].apply(lambda x: x.split('-')[1])
    df['date'] = str(year)+'-'+str("{0:0=2d}".format(month))+'-'+str("{0:0=2d}".format(day))
    df.drop(['Game', 'Location', 'ThrillScore', 'Comeback', 'Excitement',
       'ThrillScoreRank', 'ExcitementRank', 'ComebackRank', 'MVP',
       'Possessions', 'PredictedScore', 'WinProbability',
       'PredictedMOV', 'PredictedLoser', 'OT', 'Loser', 'LoserRank',
       'LoserScore', 'Winner', 'WinnerRank', 'WinnerScore', 'ActualMOV'], axis = 1, inplace = True)
    df['pw'] = df['pw'].astype(int)
    df['pl'] = df['pl'].astype(int)
    df['ps'] = df['pw'] - df['pl']
    return df

In [214]:
pkp = prediciton(2018,11,6)

In [215]:
pkp

   PredictedWinner  pw  pl        date  ps
0             Duke  78  77  2018-11-06   1
1           Kansas  79  72  2018-11-06   7
2      Florida St.  79  74  2018-11-06   5
3       Washington  80  73  2018-11-06   7
4              UCF  76  70  2018-11-06   6
..             ...  ..  ..         ...  ..
89       Villanova  93  57  2018-11-06  36
90         Alabama  83  57  2018-11-06  26
91         Indiana  88  59  2018-11-06  29
92        Nebraska  90  61  2018-11-06  29
93       Wisconsin  84  53  2018-11-06  31

[94 rows x 5 columns]

In [216]:
df2.head()

,home,away,home_score,away_score,date,line,score,cover,team_x,off_x,def_x,tempo_x,team_y,off_y,def_y,tempo_y
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1,Virginia,112.5,86.9,66.5,Towson,96.8,101.8,72.6
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1,Boston College,106.4,95.6,74.4,Milwaukee,95.7,103.0,71.5
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1,Pittsburgh,101.3,98.9,70.5,Youngstown St.,94.0,108.0,75.3
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1,Notre Dame,107.9,96.4,71.2,Illinois Chicago,98.5,100.6,76.5
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1,Western Michigan,99.0,103.1,73.0,Detroit,94.5,109.2,75.2

In [217]:
df2 = pd.merge(df2, pkp, how='left', left_on=['home','date'], right_on=['PredictedWinner','date'])
df2 = pd.merge(df2, pkp, how='left', left_on=['away','date'], right_on=['PredictedWinner','date'])

In [218]:
df2

,home,away,home_score,away_score,date,line,score,cover,team_x,off_x,def_x,tempo_x,team_y,off_y,def_y,tempo_y,PredictedWinner_x,pw_x,pl_x,ps_x,PredictedWinner_y,pw_y,pl_y,ps_y
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1,Virginia,112.5,86.9,66.5,Towson,96.8,101.8,72.6,Virginia,78.0,54.0,24.0,NaN,NaN,NaN,NaN
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1,Boston College,106.4,95.6,74.4,Milwaukee,95.7,103.0,71.5,Boston College,81.0,64.0,17.0,NaN,NaN,NaN,NaN
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1,Pittsburgh,101.3,98.9,70.5,Youngstown St.,94.0,108.0,75.3,Pittsburgh,80.0,65.0,15.0,NaN,NaN,NaN,NaN
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1,Notre Dame,107.9,96.4,71.2,Illinois Chicago,98.5,100.6,76.5,Notre Dame,82.0,68.0,14.0,NaN,NaN,NaN,NaN
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1,Western Michigan,99.0,103.1,73.0,Detroit,94.5,109.2,75.2,Western Michigan,82.0,70.0,12.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2711,Marshall,Green Bay,90.0,70.0,2019-04-04,5.5,20.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2712,DePaul,South Florida,65.0,77.0,2019-04-05,2.0,-12.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2713,Michigan St.,Texas Tech,51.0,61.0,2019-04-06,2.5,-10.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2714,Virginia,Auburn,63.0,62.0,2019-04-06,5.0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2715,Virginia,Texas Tech,85.0,77.0,2019-04-08,1.0,8.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [221]:
df2.head(100)

,home,away,home_score,away_score,date,line,score,cover,team_x,off_x,def_x,tempo_x,team_y,off_y,def_y,tempo_y,PredictedWinner_x,pw_x,pl_x,ps_x,PredictedWinner_y,pw_y,pl_y,ps_y
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1,Virginia,112.5,86.9,66.5,Towson,96.8,101.8,72.6,Virginia,78.0,54.0,24.0,NaN,NaN,NaN,NaN
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1,Boston College,106.4,95.6,74.4,Milwaukee,95.7,103.0,71.5,Boston College,81.0,64.0,17.0,NaN,NaN,NaN,NaN
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1,Pittsburgh,101.3,98.9,70.5,Youngstown St.,94.0,108.0,75.3,Pittsburgh,80.0,65.0,15.0,NaN,NaN,NaN,NaN
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1,Notre Dame,107.9,96.4,71.2,Illinois Chicago,98.5,100.6,76.5,Notre Dame,82.0,68.0,14.0,NaN,NaN,NaN,NaN
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1,Western Michigan,99.0,103.1,73.0,Detroit,94.5,109.2,75.2,Western Michigan,82.0,70.0,12.0,NaN,NaN,NaN,NaN
5,Davidson,Cleveland St.,83.0,63.0,2018-11-06,18.5,20.0,1,Davidson,107.9,99.6,71.5,Cleveland St.,95.0,105.7,72.8,Davidson,82.0,65.0,17.0,NaN,NaN,NaN,NaN
6,George Mason,Penn,71.0,72.0,2018-11-06,3.5,-1.0,0,George Mason,103.6,99.2,73.6,Penn,100.3,99.0,73.1,George Mason,76.0,71.0,5.0,NaN,NaN,NaN,NaN
7,Ball St.,Indiana St.,86.0,69.0,2018-11-06,6.5,17.0,1,Ball St.,103.7,98.7,74.3,Indiana St.,99.9,98.6,74.6,Ball St.,78.0,72.0,6.0,NaN,NaN,NaN,NaN
8,Auburn,South Alabama,101.0,58.0,2018-11-06,21.0,43.0,1,Auburn,111.2,91.6,76.6,South Alabama,99.7,100.6,76.1,Auburn,89.0,69.0,20.0,NaN,NaN,NaN,NaN
9,Temple,La Salle,75.0,67.0,2018-11-06,10.0,8.0,0,Temple,105.7,97.5,72.8,La Salle,100.6,101.5,73.4,Temple,79.0,69.0,10.0,NaN,NaN,NaN,NaN
10,Maryland,Delaware,73.0,67.0,2018-11-06,18.5,6.0,0,Maryland,110.4,93.7,72.2,Delaware,98.5,104.2,71.3,Maryland,82.0,63.0,19.0,NaN,NaN,NaN,NaN
11,Wichita St.,Louisiana Tech,58.0,71.0,2018-11-06,10.5,-13.0,0,Wichita St.,107.8,97.9,73.1,Louisiana Tech,102.7,99.7,73.2,Wichita St.,80.0,71.0,9.0,NaN,NaN,NaN,NaN
12,Xavier,IUPUI,82.0,69.0,2018-11-06,20.5,13.0,0,Xavier,108.2,96.3,73.9,IUPUI,94.6,104.4,72.2,Xavier,83.0,64.0,19.0,NaN,NaN,NaN,NaN
13,Arizona St.,Cal St. Fullerton,102.0,94.0,2018-11-06,11.5,8.0,0,Arizona St.,108.6,96.7,75.4,Cal St. Fullerton,102.0,99.5,74.2,Arizona St.,83.0,72.0,11.0,NaN,NaN,NaN,NaN
14,Florida St.,Florida,81.0,60.0,2018-11-06,4.0,21.0,1,Florida St.,112.6,92.4,75.5,Florida,109.9,90.8,73.2,Florida St.,79.0,74.0,5.0,NaN,NaN,NaN,NaN
15,Cal St. Northridge,New Mexico,84.0,87.0,2018-11-06,-13.5,-3.0,1,Cal St. Northridge,91.7,108.8,73.9,New Mexico,105.0,100.7,75.0,NaN,NaN,NaN,NaN,New Mexico,83.0,70.0,13.0
16,Oregon St.,UC Riverside,72.0,59.0,2018-11-06,18.5,13.0,0,Oregon St.,105.3,98.1,70.8,UC Riverside,92.6,104.7,73.2,Oregon St.,79.0,62.0,17.0,NaN,NaN,NaN,NaN
17,UC Davis,San Francisco,42.0,76.0,2018-11-06,2.0,-34.0,0,UC Davis,99.4,100.1,72.1,San Francisco,100.6,98.1,72.1,UC Davis,71.0,69.0,2.0,NaN,NaN,NaN,NaN
18,Wyoming,UC Santa Barbara,66.0,76.0,2018-11-06,7.5,-10.0,0,Wyoming,102.1,100.1,77.1,UC Santa Barbara,100.3,102.9,72.0,Wyoming,80.0,73.0,7.0,NaN,NaN,NaN,NaN
19,Washington,Western Kentucky,73.0,55.0,2018-11-06,5.0,18.0,1,Washington,108.1,95.1,74.4,Western Kentucky,107.3,98.7,73.2,Washington,80.0,73.0,7.0,NaN,NaN,NaN,NaN
20,Nevada,BYU,86.0,70.0,2018-11-06,12.5,16.0,1,Nevada,116.8,92.4,74.5,BYU,106.6,94.9,74.8,Nevada,85.0,72.0,13.0,NaN,NaN,NaN,NaN
21,Providence,Siena,77.0,67.0,2018-11-06,18.5,10.0,0,Providence,106.3,93.9,72.4,Siena,97.2,103.8,71.3,Providence,79.0,62.0,17.0,NaN,NaN,NaN,NaN
22,UCF,Rider,84.0,70.0,2018-11-06,6.0,14.0,1,UCF,103.0,92.8,70.9,Rider,105.0,99.0,76.5,UCF,76.0,70.0,6.0,NaN,NaN,NaN,NaN
23,Charlotte,Chattanooga,69.0,80.0,2018-11-06,5.5,-11.0,0,Charlotte,96.7,106.9,74.1,Chattanooga,93.4,106.3,71.3,Charlotte,76.0,70.0,6.0,NaN,NaN,NaN,NaN
24,Clemson,The Citadel,100.0,80.0,2018-11-06,25.0,20.0,0,Clemson,111.3,90.9,71.2,The Citadel,101.1,108.3,81.1,Clemson,94.0,69.0,25.0,NaN,NaN,NaN,NaN
25,Purdue,Fairfield,90.0,57.0,2018-11-06,21.0,33.0,1,Purdue,112.4,92.8,72.8,Fairfield,96.9,101.6,74.5,Purdue,85.0,64.0,21.0,NaN,NaN,NaN,NaN
26,Syracuse,Eastern Washington,66.0,34.0,2018-11-06,18.0,32.0,1,Syracuse,111.8,88.3,69.8,Eastern Washington,100.8,102.3,72.1,Syracuse,80.0,59.0,21.0,NaN,NaN,NaN,NaN
27,Georgia St.,East Tennessee St.,74.0,68.0,2018-11-06,7.0,6.0,0,Georgia St.,104.9,97.8,72.2,East Tennessee St.,99.4,99.2,73.3,Georgia St.,76.0,68.0,8.0,NaN,NaN,NaN,NaN
28,Wofford,North Carolina,67.0,78.0,2018-11-06,-10.0,-11.0,0,Wofford,105.9,102.1,71.3,North Carolina,115.5,90.1,75.8,NaN,NaN,NaN,NaN,North Carolina,84.0,72.0,12.0
29,UAB,Mercer,75.0,67.0,2018-11-06,7.5,8.0,1,UAB,101.7,101.4,72.5,Mercer,99.7,106.0,69.9,UAB,76.0,68.0,8.0,NaN,NaN,NaN,NaN
30,Memphis,Tennessee Tech,76.0,61.0,2018-11-06,14.0,15.0,1,Memphis,105.2,99.8,72.7,Tennessee Tech,93.4,103.4,74.9,Memphis,82.0,67.0,15.0,NaN,NaN,NaN,NaN
31,Minnesota,Nebraska Omaha,104.0,76.0,2018-11-06,15.0,28.0,1,Minnesota,107.6,96.2,74.3,Nebraska Omaha,100.8,105.1,76.0,Minnesota,87.0,72.0,15.0,NaN,NaN,NaN,NaN
32,Missouri St.,Oral Roberts,84.0,50.0,2018-11-06,6.0,34.0,1,Missouri St.,98.8,101.4,71.6,Oral Roberts,100.0,105.7,71.2,Missouri St.,74.0,69.0,5.0,NaN,NaN,NaN,NaN
33,Saint Louis,Southeast Missouri St.,75.0,65.0,2018-11-06,19.0,10.0,0,Saint Louis,104.2,93.8,70.4,Southeast Missouri St.,96.8,108.7,74.0,Saint Louis,82.0,62.0,20.0,NaN,NaN,NaN,NaN
34,SIU Edwardsville,Pacific,65.0,74.0,2018-11-06,-7.0,-9.0,0,SIU Edwardsville,94.4,107.5,73.7,Pacific,102.7,100.5,71.8,NaN,NaN,NaN,NaN,Pacific,77.0,70.0,7.0
35,Texas,Eastern Illinois,71.0,59.0,2018-11-06,25.0,12.0,0,Texas,111.1,91.4,71.7,Eastern Illinois,93.0,103.8,71.7,Texas,82.0,57.0,25.0,NaN,NaN,NaN,NaN
36,Creighton,Western Illinois,78.0,67.0,2018-11-06,20.0,11.0,0,Creighton,109.5,93.6,74.8,Western Illinois,97.1,103.1,73.4,Creighton,85.0,65.0,20.0,NaN,NaN,NaN,NaN
37,Manhattan,Elon,56.0,62.0,2018-11-06,-1.0,-6.0,0,Manhattan,92.8,102.5,72.3,Elon,100.2,104.6,73.0,NaN,NaN,NaN,NaN,Elon,72.0,71.0,1.0
38,UCLA,Purdue Fort Wayne,96.0,71.0,2018-11-06,13.5,25.0,1,UCLA,110.1,97.2,75.2,Purdue Fort Wayne,102.5,102.3,76.1,UCLA,88.0,74.0,14.0,NaN,NaN,NaN,NaN
39,Montana St.,Utah St.,71.0,101.0,2018-11-06,-2.5,-30.0,0,Montana St.,98.8,106.7,74.2,Utah St.,101.4,101.5,74.8,NaN,NaN,NaN,NaN,Utah St.,79.0,77.0,2.0
40,UC Irvine,Idaho,86.0,68.0,2018-11-06,10.5,18.0,1,UC Irvine,101.9,95.9,72.2,Idaho,97.7,103.6,71.7,UC Irvine,76.0,64.0,12.0,NaN,NaN,NaN,NaN
41,San Diego,Weber St.,83.0,66.0,2018-11-06,4.0,17.0,1,San Diego,102.3,99.5,72.8,Weber St.,103.9,100.4,72.4,San Diego,75.0,72.0,3.0,NaN,NaN,NaN,NaN
42,Oregon,Portland St.,84.0,57.0,2018-11-06,20.0,27.0,1,Oregon,109.8,92.7,72.9,Portland St.,99.6,105.0,77.7,Oregon,89.0,68.0,21.0,NaN,NaN,NaN,NaN
43,Gonzaga,Idaho St.,120.0,79.0,2018-11-06,27.5,41.0,1,Gonzaga,114.5,91.2,74.1,Idaho St.,98.5,105.7,73.2,Gonzaga,90.0,64.0,26.0,NaN,NaN,NaN,NaN
44,USC,Robert Morris,83.0,62.0,2018-11-06,19.0,21.0,1,USC,107.6,96.3,73.5,Robert Morris,93.9,101.4,73.9,USC,82.0,64.0,18.0,NaN,NaN,NaN,NaN
45,DePaul,Bethune Cookman,80.0,58.0,2018-11-07,18.5,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Northwestern,New Orleans,82.0,52.0,2018-11-08,18.0,30.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Utah,Maine,75.0,61.0,2018-11-08,22.5,14.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Green Bay,Indiana St.,74.0,78.0,2018-11-09,0.0,-4.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Elon,North Carolina,67.0,116.0,2018-11-09,-17.5,-49.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Kentucky,Southern Illinois,71.0,59.0,2018-11-09,14.5,12.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,UNC Wilmington,Stanford,59.0,72.0,2018-11-09,-3.0,-13.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,East Carolina,James Madison,72.0,73.0,2018-11-09,-2.5,-1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Auburn,Washington,88.0,66.0,2018-11-09,8.5,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Northern Illinois,Northern Kentucky,85.0,88.0,2018-11-09,-4.0,-3.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Penn,Rice,92.0,76.0,2018-11-09,15.0,16.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Texas St.,Air Force,67.0,57.0,2018-11-09,5.0,10.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Nevada,Pacific,83.0,61.0,2018-11-09,20.0,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,UC Davis,San Diego,57.0,76.0,2018-11-09,-3.5,-19.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,California,Yale,59.0,76.0,2018-11-09,-3.0,-17.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,UCLA,Long Beach St.,91.0,80.0,2018-11-09,15.5,11.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Hawaii,Portland,82.0,64.0,2018-11-09,6.0,18.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Navy,Maryland,57.0,78.0,2018-11-09,-13.5,-21.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Pittsburgh,VMI,94.0,55.0,2018-11-09,13.0,39.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,LSU,UNC Greensboro,97.0,91.0,2018-11-09,8.5,6.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Loyola Chicago,Furman,58.0,60.0,2018-11-09,9.5,-2.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Mississippi St.,Austin Peay,95.0,67.0,2018-11-09,18.5,28.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Indiana,Montana St.,80.0,35.0,2018-11-09,25.5,45.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Samford,Jacksonville St.,92.0,72.0,2018-11-09,-9.0,20.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Montana,Georgia St.,81.0,74.0,2018-11-09,5.5,7.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Oregon,Eastern Washington,81.0,47.0,2018-11-09,19.0,34.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Florida,Charleston Southern,76.0,46.0,2018-11-09,20.0,30.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Georgia,None,110.0,76.0,2018-11-09,24.5,34.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Duquesne,William & Mary,84.0,70.0,2018-11-10,4.0,14.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Mississippi,Western Michigan,90.0,64.0,2018-11-10,12.5,26.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Purdue,Ball St.,84.0,75.0,2018-11-10,13.5,9.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Saint Louis,Troy,62.0,58.0,2018-11-10,10.0,4.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Xavier,Evansville,91.0,85.0,2018-11-10,18.0,6.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Butler,Miami OH,90.0,68.0,2018-11-10,16.0,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Charlotte,Oklahoma St.,66.0,64.0,2018-11-10,-12.0,2.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,UT Arlington,Northern Iowa,74.0,65.0,2018-11-10,-4.0,9.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Oregon St.,Wyoming,83.0,64.0,2018-11-10,9.5,19.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Portland,North Texas,73.0,78.0,2018-11-10,-7.5,-5.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,UNLV,Loyola Marymount,50.0,61.0,2018-11-10,4.0,-11.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Cleveland St.,Kent St.,79.0,83.0,2018-11-10,-3.0,-4.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Syracuse,Morehead St.,84.0,70.0,2018-11-10,23.0,14.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Western Carolina,Charleston,74.0,77.0,2018-11-10,-11.0,-3.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,IUPUI,Eastern Illinois,71.0,65.0,2018-11-10,6.0,6.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,Bradley,Southeast Missouri St.,68.0,57.0,2018-11-10,15.0,11.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Western Kentucky,Tennessee Martin,86.0,71.0,2018-11-10,15.0,15.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Saint Peter's,Delaware,75.0,78.0,2018-11-10,4.5,-3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Marist,Columbia,82.0,76.0,2018-11-10,3.0,6.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Chattanooga,Eastern Kentucky,78.0,81.0,2018-11-10,5.0,-3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,Milwaukee,North Dakota,60.0,63.0,2018-11-10,5.5,-3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,Boise St.,Idaho St.,70.0,72.0,2018-11-10,14.0,-2.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Villanova,Quinnipiac,86.0,53.0,2018-11-10,24.0,33.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Belmont,Illinois St.,100.0,89.0,2018-11-10,3.0,11.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Murray St.,Wright St.,73.0,54.0,2018-11-10,3.0,19.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,San Jose St.,Southern Utah,59.0,66.0,2018-11-10,-1.0,-7.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Portland St.,UC Riverside,71.0,64.0,2018-11-10,8.0,7.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [220]:
pd.set_option('display.max_rows', 500)

In [225]:
df2['prediction'] = df2.apply(lambda x: x['ps_x'] if x['home'] == x['PredictedWinner_x'] else -x['ps_y'], axis = 1)

In [226]:
df2.head(100)

,home,away,home_score,away_score,date,line,score,cover,team_x,off_x,def_x,tempo_x,team_y,off_y,def_y,tempo_y,PredictedWinner_x,pw_x,pl_x,ps_x,PredictedWinner_y,pw_y,pl_y,ps_y,prediction
0,Virginia,Towson,73.0,42.0,2018-11-06,25.0,31.0,1,Virginia,112.5,86.9,66.5,Towson,96.8,101.8,72.6,Virginia,78.0,54.0,24.0,NaN,NaN,NaN,NaN,24.0
1,Boston College,Milwaukee,73.0,53.0,2018-11-06,17.0,20.0,1,Boston College,106.4,95.6,74.4,Milwaukee,95.7,103.0,71.5,Boston College,81.0,64.0,17.0,NaN,NaN,NaN,NaN,17.0
2,Pittsburgh,Youngstown St.,69.0,53.0,2018-11-06,14.0,16.0,1,Pittsburgh,101.3,98.9,70.5,Youngstown St.,94.0,108.0,75.3,Pittsburgh,80.0,65.0,15.0,NaN,NaN,NaN,NaN,15.0
3,Notre Dame,Illinois Chicago,84.0,67.0,2018-11-06,16.0,17.0,1,Notre Dame,107.9,96.4,71.2,Illinois Chicago,98.5,100.6,76.5,Notre Dame,82.0,68.0,14.0,NaN,NaN,NaN,NaN,14.0
4,Western Michigan,Detroit,89.0,76.0,2018-11-06,12.5,13.0,1,Western Michigan,99.0,103.1,73.0,Detroit,94.5,109.2,75.2,Western Michigan,82.0,70.0,12.0,NaN,NaN,NaN,NaN,12.0
5,Davidson,Cleveland St.,83.0,63.0,2018-11-06,18.5,20.0,1,Davidson,107.9,99.6,71.5,Cleveland St.,95.0,105.7,72.8,Davidson,82.0,65.0,17.0,NaN,NaN,NaN,NaN,17.0
6,George Mason,Penn,71.0,72.0,2018-11-06,3.5,-1.0,0,George Mason,103.6,99.2,73.6,Penn,100.3,99.0,73.1,George Mason,76.0,71.0,5.0,NaN,NaN,NaN,NaN,5.0
7,Ball St.,Indiana St.,86.0,69.0,2018-11-06,6.5,17.0,1,Ball St.,103.7,98.7,74.3,Indiana St.,99.9,98.6,74.6,Ball St.,78.0,72.0,6.0,NaN,NaN,NaN,NaN,6.0
8,Auburn,South Alabama,101.0,58.0,2018-11-06,21.0,43.0,1,Auburn,111.2,91.6,76.6,South Alabama,99.7,100.6,76.1,Auburn,89.0,69.0,20.0,NaN,NaN,NaN,NaN,20.0
9,Temple,La Salle,75.0,67.0,2018-11-06,10.0,8.0,0,Temple,105.7,97.5,72.8,La Salle,100.6,101.5,73.4,Temple,79.0,69.0,10.0,NaN,NaN,NaN,NaN,10.0
10,Maryland,Delaware,73.0,67.0,2018-11-06,18.5,6.0,0,Maryland,110.4,93.7,72.2,Delaware,98.5,104.2,71.3,Maryland,82.0,63.0,19.0,NaN,NaN,NaN,NaN,19.0
11,Wichita St.,Louisiana Tech,58.0,71.0,2018-11-06,10.5,-13.0,0,Wichita St.,107.8,97.9,73.1,Louisiana Tech,102.7,99.7,73.2,Wichita St.,80.0,71.0,9.0,NaN,NaN,NaN,NaN,9.0
12,Xavier,IUPUI,82.0,69.0,2018-11-06,20.5,13.0,0,Xavier,108.2,96.3,73.9,IUPUI,94.6,104.4,72.2,Xavier,83.0,64.0,19.0,NaN,NaN,NaN,NaN,19.0
13,Arizona St.,Cal St. Fullerton,102.0,94.0,2018-11-06,11.5,8.0,0,Arizona St.,108.6,96.7,75.4,Cal St. Fullerton,102.0,99.5,74.2,Arizona St.,83.0,72.0,11.0,NaN,NaN,NaN,NaN,11.0
14,Florida St.,Florida,81.0,60.0,2018-11-06,4.0,21.0,1,Florida St.,112.6,92.4,75.5,Florida,109.9,90.8,73.2,Florida St.,79.0,74.0,5.0,NaN,NaN,NaN,NaN,5.0
15,Cal St. Northridge,New Mexico,84.0,87.0,2018-11-06,-13.5,-3.0,1,Cal St. Northridge,91.7,108.8,73.9,New Mexico,105.0,100.7,75.0,NaN,NaN,NaN,NaN,New Mexico,83.0,70.0,13.0,-13.0
16,Oregon St.,UC Riverside,72.0,59.0,2018-11-06,18.5,13.0,0,Oregon St.,105.3,98.1,70.8,UC Riverside,92.6,104.7,73.2,Oregon St.,79.0,62.0,17.0,NaN,NaN,NaN,NaN,17.0
17,UC Davis,San Francisco,42.0,76.0,2018-11-06,2.0,-34.0,0,UC Davis,99.4,100.1,72.1,San Francisco,100.6,98.1,72.1,UC Davis,71.0,69.0,2.0,NaN,NaN,NaN,NaN,2.0
18,Wyoming,UC Santa Barbara,66.0,76.0,2018-11-06,7.5,-10.0,0,Wyoming,102.1,100.1,77.1,UC Santa Barbara,100.3,102.9,72.0,Wyoming,80.0,73.0,7.0,NaN,NaN,NaN,NaN,7.0
19,Washington,Western Kentucky,73.0,55.0,2018-11-06,5.0,18.0,1,Washington,108.1,95.1,74.4,Western Kentucky,107.3,98.7,73.2,Washington,80.0,73.0,7.0,NaN,NaN,NaN,NaN,7.0
20,Nevada,BYU,86.0,70.0,2018-11-06,12.5,16.0,1,Nevada,116.8,92.4,74.5,BYU,106.6,94.9,74.8,Nevada,85.0,72.0,13.0,NaN,NaN,NaN,NaN,13.0
21,Providence,Siena,77.0,67.0,2018-11-06,18.5,10.0,0,Providence,106.3,93.9,72.4,Siena,97.2,103.8,71.3,Providence,79.0,62.0,17.0,NaN,NaN,NaN,NaN,17.0
22,UCF,Rider,84.0,70.0,2018-11-06,6.0,14.0,1,UCF,103.0,92.8,70.9,Rider,105.0,99.0,76.5,UCF,76.0,70.0,6.0,NaN,NaN,NaN,NaN,6.0
23,Charlotte,Chattanooga,69.0,80.0,2018-11-06,5.5,-11.0,0,Charlotte,96.7,106.9,74.1,Chattanooga,93.4,106.3,71.3,Charlotte,76.0,70.0,6.0,NaN,NaN,NaN,NaN,6.0
24,Clemson,The Citadel,100.0,80.0,2018-11-06,25.0,20.0,0,Clemson,111.3,90.9,71.2,The Citadel,101.1,108.3,81.1,Clemson,94.0,69.0,25.0,NaN,NaN,NaN,NaN,25.0
25,Purdue,Fairfield,90.0,57.0,2018-11-06,21.0,33.0,1,Purdue,112.4,92.8,72.8,Fairfield,96.9,101.6,74.5,Purdue,85.0,64.0,21.0,NaN,NaN,NaN,NaN,21.0
26,Syracuse,Eastern Washington,66.0,34.0,2018-11-06,18.0,32.0,1,Syracuse,111.8,88.3,69.8,Eastern Washington,100.8,102.3,72.1,Syracuse,80.0,59.0,21.0,NaN,NaN,NaN,NaN,21.0
27,Georgia St.,East Tennessee St.,74.0,68.0,2018-11-06,7.0,6.0,0,Georgia St.,104.9,97.8,72.2,East Tennessee St.,99.4,99.2,73.3,Georgia St.,76.0,68.0,8.0,NaN,NaN,NaN,NaN,8.0
28,Wofford,North Carolina,67.0,78.0,2018-11-06,-10.0,-11.0,0,Wofford,105.9,102.1,71.3,North Carolina,115.5,90.1,75.8,NaN,NaN,NaN,NaN,North Carolina,84.0,72.0,12.0,-12.0
29,UAB,Mercer,75.0,67.0,2018-11-06,7.5,8.0,1,UAB,101.7,101.4,72.5,Mercer,99.7,106.0,69.9,UAB,76.0,68.0,8.0,NaN,NaN,NaN,NaN,8.0
30,Memphis,Tennessee Tech,76.0,61.0,2018-11-06,14.0,15.0,1,Memphis,105.2,99.8,72.7,Tennessee Tech,93.4,103.4,74.9,Memphis,82.0,67.0,15.0,NaN,NaN,NaN,NaN,15.0
31,Minnesota,Nebraska Omaha,104.0,76.0,2018-11-06,15.0,28.0,1,Minnesota,107.6,96.2,74.3,Nebraska Omaha,100.8,105.1,76.0,Minnesota,87.0,72.0,15.0,NaN,NaN,NaN,NaN,15.0
32,Missouri St.,Oral Roberts,84.0,50.0,2018-11-06,6.0,34.0,1,Missouri St.,98.8,101.4,71.6,Oral Roberts,100.0,105.7,71.2,Missouri St.,74.0,69.0,5.0,NaN,NaN,NaN,NaN,5.0
33,Saint Louis,Southeast Missouri St.,75.0,65.0,2018-11-06,19.0,10.0,0,Saint Louis,104.2,93.8,70.4,Southeast Missouri St.,96.8,108.7,74.0,Saint Louis,82.0,62.0,20.0,NaN,NaN,NaN,NaN,20.0
34,SIU Edwardsville,Pacific,65.0,74.0,2018-11-06,-7.0,-9.0,0,SIU Edwardsville,94.4,107.5,73.7,Pacific,102.7,100.5,71.8,NaN,NaN,NaN,NaN,Pacific,77.0,70.0,7.0,-7.0
35,Texas,Eastern Illinois,71.0,59.0,2018-11-06,25.0,12.0,0,Texas,111.1,91.4,71.7,Eastern Illinois,93.0,103.8,71.7,Texas,82.0,57.0,25.0,NaN,NaN,NaN,NaN,25.0
36,Creighton,Western Illinois,78.0,67.0,2018-11-06,20.0,11.0,0,Creighton,109.5,93.6,74.8,Western Illinois,97.1,103.1,73.4,Creighton,85.0,65.0,20.0,NaN,NaN,NaN,NaN,20.0
37,Manhattan,Elon,56.0,62.0,2018-11-06,-1.0,-6.0,0,Manhattan,92.8,102.5,72.3,Elon,100.2,104.6,73.0,NaN,NaN,NaN,NaN,Elon,72.0,71.0,1.0,-1.0
38,UCLA,Purdue Fort Wayne,96.0,71.0,2018-11-06,13.5,25.0,1,UCLA,110.1,97.2,75.2,Purdue Fort Wayne,102.5,102.3,76.1,UCLA,88.0,74.0,14.0,NaN,NaN,NaN,NaN,14.0
39,Montana St.,Utah St.,71.0,101.0,2018-11-06,-2.5,-30.0,0,Montana St.,98.8,106.7,74.2,Utah St.,101.4,101.5,74.8,NaN,NaN,NaN,NaN,Utah St.,79.0,77.0,2.0,-2.0
40,UC Irvine,Idaho,86.0,68.0,2018-11-06,10.5,18.0,1,UC Irvine,101.9,95.9,72.2,Idaho,97.7,103.6,71.7,UC Irvine,76.0,64.0,12.0,NaN,NaN,NaN,NaN,12.0
41,San Diego,Weber St.,83.0,66.0,2018-11-06,4.0,17.0,1,San Diego,102.3,99.5,72.8,Weber St.,103.9,100.4,72.4,San Diego,75.0,72.0,3.0,NaN,NaN,NaN,NaN,3.0
42,Oregon,Portland St.,84.0,57.0,2018-11-06,20.0,27.0,1,Oregon,109.8,92.7,72.9,Portland St.,99.6,105.0,77.7,Oregon,89.0,68.0,21.0,NaN,NaN,NaN,NaN,21.0
43,Gonzaga,Idaho St.,120.0,79.0,2018-11-06,27.5,41.0,1,Gonzaga,114.5,91.2,74.1,Idaho St.,98.5,105.7,73.2,Gonzaga,90.0,64.0,26.0,NaN,NaN,NaN,NaN,26.0
44,USC,Robert Morris,83.0,62.0,2018-11-06,19.0,21.0,1,USC,107.6,96.3,73.5,Robert Morris,93.9,101.4,73.9,USC,82.0,64.0,18.0,NaN,NaN,NaN,NaN,18.0
45,DePaul,Bethune Cookman,80.0,58.0,2018-11-07,18.5,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Northwestern,New Orleans,82.0,52.0,2018-11-08,18.0,30.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Utah,Maine,75.0,61.0,2018-11-08,22.5,14.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Green Bay,Indiana St.,74.0,78.0,2018-11-09,0.0,-4.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Elon,North Carolina,67.0,116.0,2018-11-09,-17.5,-49.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Kentucky,Southern Illinois,71.0,59.0,2018-11-09,14.5,12.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,UNC Wilmington,Stanford,59.0,72.0,2018-11-09,-3.0,-13.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,East Carolina,James Madison,72.0,73.0,2018-11-09,-2.5,-1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Auburn,Washington,88.0,66.0,2018-11-09,8.5,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Northern Illinois,Northern Kentucky,85.0,88.0,2018-11-09,-4.0,-3.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Penn,Rice,92.0,76.0,2018-11-09,15.0,16.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Texas St.,Air Force,67.0,57.0,2018-11-09,5.0,10.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Nevada,Pacific,83.0,61.0,2018-11-09,20.0,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,UC Davis,San Diego,57.0,76.0,2018-11-09,-3.5,-19.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,California,Yale,59.0,76.0,2018-11-09,-3.0,-17.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,UCLA,Long Beach St.,91.0,80.0,2018-11-09,15.5,11.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Hawaii,Portland,82.0,64.0,2018-11-09,6.0,18.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Navy,Maryland,57.0,78.0,2018-11-09,-13.5,-21.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Pittsburgh,VMI,94.0,55.0,2018-11-09,13.0,39.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,LSU,UNC Greensboro,97.0,91.0,2018-11-09,8.5,6.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Loyola Chicago,Furman,58.0,60.0,2018-11-09,9.5,-2.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Mississippi St.,Austin Peay,95.0,67.0,2018-11-09,18.5,28.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Indiana,Montana St.,80.0,35.0,2018-11-09,25.5,45.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Samford,Jacksonville St.,92.0,72.0,2018-11-09,-9.0,20.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Montana,Georgia St.,81.0,74.0,2018-11-09,5.5,7.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Oregon,Eastern Washington,81.0,47.0,2018-11-09,19.0,34.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Florida,Charleston Southern,76.0,46.0,2018-11-09,20.0,30.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Georgia,None,110.0,76.0,2018-11-09,24.5,34.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Duquesne,William & Mary,84.0,70.0,2018-11-10,4.0,14.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Mississippi,Western Michigan,90.0,64.0,2018-11-10,12.5,26.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Purdue,Ball St.,84.0,75.0,2018-11-10,13.5,9.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Saint Louis,Troy,62.0,58.0,2018-11-10,10.0,4.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Xavier,Evansville,91.0,85.0,2018-11-10,18.0,6.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Butler,Miami OH,90.0,68.0,2018-11-10,16.0,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Charlotte,Oklahoma St.,66.0,64.0,2018-11-10,-12.0,2.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,UT Arlington,Northern Iowa,74.0,65.0,2018-11-10,-4.0,9.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Oregon St.,Wyoming,83.0,64.0,2018-11-10,9.5,19.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Portland,North Texas,73.0,78.0,2018-11-10,-7.5,-5.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,UNLV,Loyola Marymount,50.0,61.0,2018-11-10,4.0,-11.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Cleveland St.,Kent St.,79.0,83.0,2018-11-10,-3.0,-4.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Syracuse,Morehead St.,84.0,70.0,2018-11-10,23.0,14.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Western Carolina,Charleston,74.0,77.0,2018-11-10,-11.0,-3.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,IUPUI,Eastern Illinois,71.0,65.0,2018-11-10,6.0,6.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,Bradley,Southeast Missouri St.,68.0,57.0,2018-11-10,15.0,11.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Western Kentucky,Tennessee Martin,86.0,71.0,2018-11-10,15.0,15.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Saint Peter's,Delaware,75.0,78.0,2018-11-10,4.5,-3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Marist,Columbia,82.0,76.0,2018-11-10,3.0,6.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Chattanooga,Eastern Kentucky,78.0,81.0,2018-11-10,5.0,-3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,Milwaukee,North Dakota,60.0,63.0,2018-11-10,5.5,-3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,Boise St.,Idaho St.,70.0,72.0,2018-11-10,14.0,-2.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Villanova,Quinnipiac,86.0,53.0,2018-11-10,24.0,33.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Belmont,Illinois St.,100.0,89.0,2018-11-10,3.0,11.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Murray St.,Wright St.,73.0,54.0,2018-11-10,3.0,19.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,San Jose St.,Southern Utah,59.0,66.0,2018-11-10,-1.0,-7.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Portland St.,UC Riverside,71.0,64.0,2018-11-10,8.0,7.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [227]:
df2.columns

Index(['home', 'away', 'home_score', 'away_score', 'date', 'line', 'score',
       'cover', 'team_x', 'off_x', 'def_x', 'tempo_x', 'team_y', 'off_y',
       'def_y', 'tempo_y', 'PredictedWinner_x', 'pw_x', 'pl_x', 'ps_x',
       'PredictedWinner_y', 'pw_y', 'pl_y', 'ps_y', 'prediction'],
      dtype='object')

In [229]:
df2

,home,away,date,line,score,cover,team_x,off_x,def_x,tempo_x,team_y,off_y,def_y,tempo_y,prediction
0,Virginia,Towson,2018-11-06,25.0,31.0,1,Virginia,112.5,86.9,66.5,Towson,96.8,101.8,72.6,24.0
1,Boston College,Milwaukee,2018-11-06,17.0,20.0,1,Boston College,106.4,95.6,74.4,Milwaukee,95.7,103.0,71.5,17.0
2,Pittsburgh,Youngstown St.,2018-11-06,14.0,16.0,1,Pittsburgh,101.3,98.9,70.5,Youngstown St.,94.0,108.0,75.3,15.0
3,Notre Dame,Illinois Chicago,2018-11-06,16.0,17.0,1,Notre Dame,107.9,96.4,71.2,Illinois Chicago,98.5,100.6,76.5,14.0
4,Western Michigan,Detroit,2018-11-06,12.5,13.0,1,Western Michigan,99.0,103.1,73.0,Detroit,94.5,109.2,75.2,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2711,Marshall,Green Bay,2019-04-04,5.5,20.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2712,DePaul,South Florida,2019-04-05,2.0,-12.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2713,Michigan St.,Texas Tech,2019-04-06,2.5,-10.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2714,Virginia,Auburn,2019-04-06,5.0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2715,Virginia,Texas Tech,2019-04-08,1.0,8.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [228]:
df2.drop(['home_score', 'away_score','PredictedWinner_x', 'pw_x', 'pl_x', 'ps_x',
       'PredictedWinner_y', 'pw_y', 'pl_y', 'ps_y','team_x','team_y'], axis = 1, inplace = True)